<?php

namespace common\models;

use Yii;
/**
 * Team: @NKL,NKU
 * Coding by 孙家宜 1810756
 * This is the model class for table "cov_news" generated by gii.
 */

/**
 * This is the model class for table "{{%news}}".
 *
 * @property int $id
 * @property string|null $pubDate
 * @property string|null $title
 * @property string|null $summary
 * @property string|null $infoSource
 * @property string|null $sourceUrl
 * @property string|null $crawlTime
 */
class CovNews extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%news}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['pubDate', 'title', 'infoSource', 'sourceUrl', 'crawlTime'], 'string', 'max' => 255],
            [['summary'], 'string', 'max' => 2000],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pubDate' => 'Pub Date',
            'title' => 'Title',
            'summary' => 'Summary',
            'infoSource' => 'Info Source',
            'sourceUrl' => 'Source Url',
            'crawlTime' => 'Crawl Time',
        ];
    }
}